#!/usr/bin/env perl
use strict;
use warnings;

my @scripts = qw/
    smartfm-divergence
    reading-newlines
    reading-typos
    dictionary-translations
/;

for my $script (@scripts) {
    print "$script:\n";
    system($script);
    print "\n";
}

