#!/usr/bin/env perl
use 5.14.0;
use warnings;
use utf8::all;
use Anki::Database;
use List::Util 'first';

my $db = Anki::Database->new;
my $sth = $db->prepare(q{
    select context.factId, context.value
    from fields as context
    join fieldModels on (context.fieldModelId = fieldModels.id)
    where
        fieldModels.name = '前後関係'
        and context.value like '%ibid%'
;});

$sth->execute;

my $printed_header = 0;
while (my ($fid, $context) = $sth->fetchrow_array) {
    say "=== INVALID CONTEXT ===" if $printed_header++ == 0;
    say "$fid|$context";
}

$sth = $db->prepare(q{
    select context.factId, context.value
    from fields as context
    join fieldModels as contextFM on (context.fieldModelId = contextFM.id)
    join facts as contextFact on (context.factId = contextFact.id)
    where
        contextFM.name = '前後関係'
        and contextFact.tags like '%context-only%'
        and context.value = ''
;});

$sth->execute;

$printed_header = 0;
while (my ($fid, $context) = $sth->fetchrow_array) {
    say "=== HAS TAG context-only WITHOUT CONTEXT ===" if $printed_header++ == 0;
    say "$fid|$context";
}


