#!/usr/bin/env perl
use 5.14.0;
use warnings;
use Anki::Database;
use utf8::all;

my $db = Anki::Database->new;
my $sth = $db->prepare("
    select fields.value from fields
    join fieldModels on (fields.fieldModelId = fieldModels.id)
    where
        fieldModels.name = '日本語'
        and factId in (
            select factId from fields
            join fieldModels on (fields.fieldModelId = fieldModels.id)
            where
                fieldModels.name = '出所'
                and fields.value in ('プログレッシブ英和・和英中辞典', 'Smart.fm')
                and factId in (
                    select factId from fields
                    join fieldModels on (fields.fieldModelId = fieldModels.id)
                    where
                        fieldModels.name = '翻訳'
                        and fields.value = ''
                )
        )
;");

$sth->execute;

while (my ($sentence) = $sth->fetchrow_array) {
    say $sentence;
}

