#!/usr/bin/env perl
use 5.14.0;
use warnings;
use utf8::all;
use Anki::Database;

my $db = Anki::Database->new(file => $ENV{ANKI_DECK});
my $sth = $db->prepare("
    select kanji.value, cards.noCount, cards.reps, (100 * cards.yesCount) / cards.reps as difficulty
    from fields as kanji
        join fieldModels on (kanji.fieldModelId = fieldModels.id)
        join fields as reading on (kanji.factId = reading.factId)
        join cards on (cards.factId = kanji.factId)
        join cardModels on (cards.cardModelId = cardModels.id)
    where
        fieldModels.name = '漢字'
        and cardModels.name = '書け'
        and reading.value = ''
        and cards.noCount > 5
        order by difficulty asc
        limit 20
;");

$sth->execute;

while (my ($kanji, $wrong, $reps, $difficulty) = $sth->fetchrow_array) {
    say sprintf "%s: %d/%d (%d%%)", $kanji, $wrong, $reps, $difficulty;
}

__END__
朗: 11/32 (65%)
縦: 7/22 (68%)
隊: 7/23 (69%)
封: 8/26 (69%)
迅: 6/22 (72%)
築: 6/22 (72%)
堕: 7/26 (73%)
柔: 8/30 (73%)
漆: 7/26 (73%)
賠: 16/61 (73%)
慰: 14/54 (74%)
統: 7/29 (75%)
縁: 7/28 (75%)
韻: 16/65 (75%)
紡: 8/34 (76%)
塀: 6/26 (76%)
婿: 6/25 (76%)
茹: 7/30 (76%)
硝: 7/31 (77%)
袋: 8/36 (77%)
