#!/usr/bin/env perl
use 5.14.0;
use warnings;
use utf8::all;
use Anki::Morphology;
use List::MoreUtils 'any';

my $sentence = join ' ', @ARGV
    or die "usage: $0 word\n";
my $morph = Anki::Morphology->new;
my $corpus = $morph->corpus;

my @word_morphemes = map { $_->{dictionary} } $morph->morphemes_of($sentence);
warn "$sentence does not produce exactly one morpheme: " . join(', ', @word_morphemes)
    if @word_morphemes != 1;

my %i = map { $_ => 1 } $morph->known_morphemes, @word_morphemes;

my $morph_pattern = '"% ' . join(' ', @word_morphemes) . ' %"';
my $order = $corpus->order;
my $sth = $corpus->prepare("
    SELECT rowid, japanese, morphemes
    FROM sentences
    WHERE suspended = 1
    AND morphemes LIKE $morph_pattern
    ORDER BY $order
;");
$sth->execute;

while (my ($rowid, $sentence, $morphemes) = $sth->fetchrow_array) {
    next if any { !$i{ $_ } } split ' ', $morphemes;
    say "$rowid: $sentence";
}
