#!/usr/bin/env perl
use 5.14.0;
use warnings;
use Anki::Database;
use utf8::all;

my $db = Anki::Database->new;
my $sth = $db->prepare("
    select facts.id
    from facts
        join cards on (cards.factId = facts.id)
    where
        facts.tags like '%Marked%'
        or cards.tags like '%Marked%'
;");

$sth->execute;

my $i = 0;
while (my ($fid) = $sth->fetchrow_array) {
    say $fid;
}

