#!/usr/bin/env perl
use 5.14.0;
use warnings;
use Anki::Database;
use utf8::all;

my $db = Anki::Database->new;
my $sth = $db->prepare("
    select sentence.factId, sentence.value, reading.value
    from fields as sentence
        join fields as reading on (sentence.factId = reading.factId)
        join cards as sentence_card on (sentence.factId = sentence_card.factId)
        join fieldModels as sentenceModel on (sentence.fieldModelId = sentenceModel.id)
        join fieldModels as readingModel on (reading.fieldModelId = readingModel.id)
        join models on (sentenceModel.modelId = models.id)
    where
        models.name = '文'
        and readingModel.name = '読み'
        and sentenceModel.name = '日本語'
        and sentence_card.type >= 0;
");

$sth->execute;

while (my ($fid, $sentence, $reading_field) = $sth->fetchrow_array) {
    my @needed;
    for my $kanji ($sentence =~ /(\p{Han}|[０１２３４５６７８９])/g) {
        next if $reading_field =~ $kanji;
        push @needed, $kanji;
    }
    next if !@needed;

    say "$fid|$sentence";
    say "  " . join ', ', @needed;
}

