#!/bin/sh
# find kanji with only a few sentences which is a good indicator that I don't
# really know that kanji's readings yet

echo "select kanji.value, group_concat(sentence.value, '|')
    from fields as kanji
        join fields as sentence on (sentence.value like ('%'||kanji.value||'%'))
        join cards as sentence_card on (sentence.factId = sentence_card.factId)
    where
        sentence.fieldModelId=4775683831775348908
        and kanji.fieldModelId=7694462791390410032
        and sentence_card.type>0
        group by kanji.value
        having count(sentence.value) < 4
        order by count(sentence.value)
;" | sqlite3 ~/Documents/Anki/Japanese.anki

