#!/bin/sh
echo 'select fields.value from fields join fieldModels on (fields.fieldModelId = fieldModels.id) where fieldModels.name like "%読み%" and fields.value like "%】%【%" and fields.value not like "%<br%";' | sqlite3 $ANKI_DECK
