#!/usr/bin/env perl
use 5.14.0;
use warnings;
use utf8::all;
use Anki::Database;
use Anki::Corpus;
use List::MoreUtils 'all';
use Array::Diff;

my $japanese_db = Anki::Database->new;

my $sth = $japanese_db->prepare("
    select sentence.value
    from fields as sentence
        join fields as source on (source.factId = sentence.factId)
        join fieldModels as sentenceModel on (sentence.fieldModelId = sentenceModel.id)
        join fieldModels as sourceModel on (source.fieldModelId = sourceModel.id)
    where
        sentenceModel.name = '日本語'
        and sourceModel.name = '出所'
        and source.value = 'Smart.fm'
;");
$sth->execute;
my @japanese = sort map { $_->[0] } @{ $sth->fetchall_arrayref };

my $corpus = Anki::Corpus->new;
$sth = $corpus->prepare("
    SELECT japanese
    FROM sentences
    WHERE suspended = 0
    AND source = 'Smart.fm'
;");
$sth->execute;
my @smart = sort map { $_->[0] } @{ $sth->fetchall_arrayref };

my $diff = Array::Diff->diff(\@smart, \@japanese);
say "+$_" for @{ $diff->added };
say "-$_" for @{ $diff->deleted };

