#!/usr/bin/env perl
use 5.14.0;
use warnings;
use utf8::all;
use Anki::Database;

my $db = Anki::Database->new(file => $ENV{ANKI_DECK});
my $sth = $db->prepare("
    select sentence.value, context.value, reading.value
    from fields as sentence
        join fields as reading on (sentence.factId = reading.factId)
        join fields as context on (sentence.factId = context.factId)
    where
        reading.fieldModelId=-988607031910086482
        and sentence.fieldModelId=4775683831775348908
        and context.fieldModelId=-404297951624436245
        and reading.value<>'';
");

$sth->execute;

my $i = 0;
while (my ($sentence, $context, $reading_field) = $sth->fetchrow_array) {
    my @readings = map { /^([^【]+)/ } split /<br.*?>/, $reading_field;
    my @spurious;
    for my $kanji (grep defined, map { /(\p{Han}+)/g } @readings) {
        my $regex = join 'っ*', split '', $kanji;
        next if "$sentence$context" =~ $regex;
        push @spurious, $kanji;
    }
    next if !@spurious;

    say ++$i . ". " . $sentence;
    say "    $_" for @spurious;
}

__END__
real sample output:

誰と会ってみたいですか。
    合
もし時間が合ったらスカイプでも話そう！
    会
正規表現, 本っっ当に面白いですねぇ
    本当
記憶はつながってる
    暗記
次はいつ会いましょうか。
    合
今，大地震が起きたと仮定したらまずどうしますか
    大地獄
