#!/usr/bin/env perl
use 5.14.0;
use warnings;
use utf8::all;
use Anki::Database;

my $db = Anki::Database->new;
my $sth = $db->prepare("
    select facts.id
    from facts
        join cards on (cards.factId = facts.id)
    where
        cards.type < 0
        and facts.tags like '%自愛%'
;");
$sth->execute;

while (my ($fid) = $sth->fetchrow_array) {
    say $fid;
}
