#!/usr/bin/env perl
use 5.14.0;
use warnings;
use utf8::all;
use Anki::Database;

my $db = Anki::Database->new(file => $ENV{ANKI_DECK});
my $sth = $db->prepare("
    select source.value, count(*)
    from fields as source
        join fieldModels on (source.fieldModelId = fieldModels.id)
        join cards on (cards.factId = source.factId)
    where
        fieldModels.name = '起こり'
        and cards.type < 0
    group by source.value
    order by count(*) desc
;");

$sth->execute;
my $total;
while (my ($source, $count) = $sth->fetchrow_array) {
    say "$source: $count";
    $total += $count;
}

say "Total: $total";

