#!/usr/bin/env perl
use 5.14.0;
use warnings;
use utf8::all;
use Anki::Database;

my $db = Anki::Database->new;
my $sth = $db->prepare("
    select sentence.factId, sentence.value
    from fields as sentence
        join fields as source on (sentence.factId = source.factId)
        join fieldModels as sentenceFM on (sentenceFM.id = sentence.fieldModelId)
        join fieldModels as sourceFM on (sourceFM.id = source.fieldModelId)
        join cards on (sentence.factId = cards.factId)
    where
        cards.type < 0
        and sourceFM.name = '出所'
        and sentenceFM.name = '日本語'
        and (
            source.value = 'Tae Kim'
            or source.value like 'http://%guidetojapanese.org/%'
        )
    order by cards.created ASC
;");
$sth->execute;

while (my ($fid, $sentence) = $sth->fetchrow_array) {
    say "$fid|$sentence";
}
